### ISSUE TITLE
Cannot read properties of null (reading 'serverDonation_address“

### ISSUE THREAD

**Issue by hhfcvmars** [lucky2077/atomicals-electrumx-docker#10]
访问 http://[localhost:8080/proxy/health](http://localhost:8080/proxy/health) 提示，需要检查哪里

 "message": "Cannot read properties of null (reading 'serverDonation_address')"

![image](https://github.com/Next-DAO/atomicals-electrumx-docker/assets/62316749/f549363c-a02b-4630-91b9-614e2cc8a8a4)

**Comment by Ronchuan11x** [comment]
老哥解决了吗

**Comment by righBai** [comment]
老哥解决了吗

**Comment by righBai** [comment]
解决了
![image](https://github.com/Next-DAO/atomicals-electrumx-docker/assets/124546333/6c93326d-37e4-4ead-93d5-0864f1ec3d0f)

**Comment by yuutmoo** [comment]
怎么解决的呢
