### ISSUE TITLE
local端口可以打开返回success，但是docker端口仍然报ERROR:Daemon:daemon service refused: Unauthorized

### ISSUE THREAD

**Issue by szhang67** [lucky2077/atomicals-electrumx-docker#11]
![微信截图_20231125042127](https://github.com/Next-DAO/atomicals-electrumx-docker/assets/30703276/8acb5a66-b762-4992-9c84-a04db492edbb)

请问这个情况正常吗？需要怎么解决，感谢

**Comment by lucky2077** [comment]
停止节点，`docker-compose down`

重启 docker，然后再 `docker-compose up -d`

如果不行，卸载 docker 重新安装试试
