### ISSUE TITLE
ERROR:Daemon:connection problem - check your daemon is running.  Retrying occasionally...

### ISSUE THREAD

**Issue by albertzzzzzzzzzzzz** [lucky2077/atomicals-electrumx-docker#12]
docker-compose up后一直提示ERROR:Daemon:connection problem - check your daemon is running.  Retrying occasionally...
这个需要在哪方面进行检查？

electrumx_1  | INFO:electrumx:ElectrumX server starting
electrumx_1  | INFO:electrumx:logging level: INFO
electrumx_1  | INFO:Controller:Python version: 3.9.18 (main, Nov 21 2023, 19:16:28)  [GCC 10.2.1 20210110]
electrumx_1  | INFO:Controller:software version: ElectrumX 1.16.0
electrumx_1  | INFO:Controller:aiorpcX version: 0.18.7
electrumx_1  | INFO:Controller:supported protocol versions: 1.4-1.4.2
electrumx_1  | INFO:Controller:event loop policy: <uvloop.EventLoopPolicy object at 0x7fa7581ce4c0>
electrumx_1  | INFO:Controller:reorg limit is 200 blocks
electrumx_1  | INFO:Daemon:daemon #1 at 127.0.0.1:8332/ (current)
electrumx_1  | INFO:DB:switching current directory to /data
electrumx_1  | INFO:DB:using leveldb for DB backend
electrumx_1  | ERROR:Daemon:connection problem - check your daemon is running.  Retrying occasionally...

electrumx_1  | ERROR:Daemon:connection problem - check your daemon is running.  Retrying occasionally...

**Comment by lucky2077** [comment]
#6
