### ISSUE TITLE
docker-compose up -d 后，一直报错 electrumx:ElectrumX server terminated abnormally

### ISSUE THREAD

**Issue by derekchan10** [lucky2077/atomicals-electrumx-docker#19]
electrumx_1  | INFO:SessionManager:RPC server listening on 0.0.0.0:8000
electrumx_1  | INFO:Prefetcher:catching up to daemon height 828,192 (3 blocks behind)
electrumx_1  | INFO:Prefetcher:cancelled; prefetcher stopping
electrumx_1  | INFO:SessionManager:closing down server for rpc://0.0.0.0:8000
electrumx_1  | INFO:Controller:shutting down
electrumx_1  | INFO:Controller:shutdown complete
electrumx_1  | ERROR:electrumx:ElectrumX server terminated abnormally
electrumx_1  | Traceback (most recent call last):
electrumx_1  |   File "/electrumx/electrumx_server", line 43, in main
electrumx_1  |     asyncio.run(controller.run())
electrumx_1  |   File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
electrumx_1  |     return loop.run_until_complete(main)
electrumx_1  |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
electrumx_1  |   File "/electrumx/electrumx/lib/server_base.py", line 129, in run
electrumx_1  |     await server_task
electrumx_1  |   File "/electrumx/electrumx/lib/server_base.py", line 102, in serve
electrumx_1  |     await self.serve(shutdown_event)
electrumx_1  |   File "/electrumx/electrumx/server/controller.py", line 137, in serve
electrumx_1  |     await group.spawn(wait_for_catchup())
electrumx_1  |   File "/usr/local/lib/python3.9/site-packages/aiorpcx/curio.py", line 297, in __aexit__
electrumx_1  |     await self.join()
electrumx_1  |   File "/electrumx/electrumx/lib/util.py", line 370, in join
electrumx_1  |     task.result()
electrumx_1  |   File "/electrumx/electrumx/server/block_processor.py", line 3405, in fetch_and_process_blocks
electrumx_1  |     await group.spawn(self._process_prefetched_blocks())
electrumx_1  |   File "/usr/local/lib/python3.9/site-packages/aiorpcx/curio.py", line 297, in __aexit__
electrumx_1  |     await self.join()
electrumx_1  |   File "/electrumx/electrumx/lib/util.py", line 370, in join
electrumx_1  |     task.result()
electrumx_1  |   File "/electrumx/electrumx/server/block_processor.py", line 3365, in _process_prefetched_blocks
electrumx_1  |     await self.check_and_advance_blocks(blocks)
electrumx_1  |   File "/electrumx/electrumx/server/block_processor.py", line 315, in check_and_advance_blocks
electrumx_1  |     await self.run_in_thread_with_lock(self.advance_blocks, blocks)
electrumx_1  |   File "/electrumx/electrumx/server/block_processor.py", line 298, in run_in_thread_with_lock
electrumx_1  |     return await asyncio.shield(run_in_thread_locked())
electrumx_1  |   File "/electrumx/electrumx/server/block_processor.py", line 297, in run_in_thread_locked
electrumx_1  |     return await run_in_thread(func, *args)
electrumx_1  |   File "/usr/local/lib/python3.9/site-packages/aiorpcx/curio.py", line 57, in run_in_thread
electrumx_1  |     return await get_event_loop().run_in_executor(None, func, *args)
electrumx_1  |   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
electrumx_1  |     result = self.fn(*self.args, **self.kwargs)
electrumx_1  |   File "/electrumx/electrumx/server/block_processor.py", line 499, in advance_blocks
electrumx_1  |     undo_info, atomicals_undo_info = self.advance_txs(block.transactions, is_unspendable, block.header, height)
electrumx_1  |   File "/electrumx/electrumx/server/block_processor.py", line 2780, in advance_txs
electrumx_1  |     blueprint_builder = self.color_atomicals_outputs(atomicals_operations_found_at_inputs, atomicals_spent_at_inputs, tx, tx_hash, tx_num, height)
electrumx_1  |   File "/electrumx/electrumx/server/block_processor.py", line 1651, in color_atomicals_outputs
electrumx_1  |     blueprint_builder = AtomicalsTransferBlueprintBuilder(self.logger, atomicals_spent_at_inputs, operations_found_at_inputs, tx_hash, tx, self.get_atomicals_id_mint_info, self.is_dmint_activated(height))
electrumx_1  |   File "/electrumx/electrumx/lib/atomicals_blueprint_builder.py", line 191, in __init__
electrumx_1  |     nft_output_blueprint, ft_output_blueprint = AtomicalsTransferBlueprintBuilder.calculate_output_blueprint(self.get_atomicals_id_mint_info, self.tx, self.nft_atomicals, self.ft_atomicals, self.atomicals_spent_at_inputs, self.operations_found_at_inputs, self.sort_fifo)
electrumx_1  |   File "/electrumx/electrumx/lib/atomicals_blueprint_builder.py", line 395, in calculate_output_blueprint
electrumx_1  |     nft_blueprint = AtomicalsTransferBlueprintBuilder.calculate_output_blueprint_nfts(get_atomicals_id_mint_info, tx, nft_atomicals, atomicals_spent_at_inputs, operations_found_at_inputs, sort_fifo)
electrumx_1  |   File "/electrumx/electrumx/lib/atomicals_blueprint_builder.py", line 313, in calculate_output_blueprint_nfts
electrumx_1  |     nft_map = AtomicalsTransferBlueprintBuilder.build_nft_input_idx_to_atomical_map(get_atomicals_id_mint_info, atomicals_spent_at_inputs)
electrumx_1  |   File "/electrumx/electrumx/lib/atomicals_blueprint_builder.py", line 250, in build_nft_input_idx_to_atomical_map
electrumx_1  |     assert(exponent == 0)
electrumx_1  | AssertionError

**Comment by lucky2077** [comment]
重新同步应该可以解决问题
