### ISSUE TITLE
同步问题

### ISSUE THREAD

**Issue by allenherrera137** [lucky2077/atomicals-electrumx-docker#2]
@lucky2077 这个一般要同步多久？ 是从创世区块开始同步吗？，还是可以指定特定高度开始同步

**Comment by lucky2077** [comment]
从0开始，大概两天左右

**Comment by allenherrera137** [comment]
感觉atom协议这个索引器搞复杂了，没必要为了自己协议的内容把所有区块重新同步一遍，占用那么多存储空间，就从808080,atom协议开始发布的区块开始。

**Comment by allenherrera137** [comment]
@lucky2077 现在同步好慢啊，是因为CACHE_MB设置太小的原因吗，感谢解答

**Comment by lucky2077** [comment]
> @lucky2077 现在同步好慢啊，是因为CACHE_MB设置太小的原因吗，感谢解答

根据官方文档，改 CACHE_MB 并不会有多少影响，并且建议不要超过 2000 ，具体为什么我也不清楚
