### ISSUE TITLE
是否可以使用网络上的节点供应商的服务

### ISSUE THREAD

**Issue by FrozenRaspberry** [lucky2077/atomicals-electrumx-docker#4]
如果我自己搭建全节点有困难的话，是否可以使用网上例如QuickNode, getblock 这类供应商提供的 rpc服务？

他们提供的接入地址是类似这样的：
https://go.getblock.io/f9661416261xxxxxxxxxxxxxxx
https://polished-rough-road.btc.quiknode.pro/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/

这能满足运行的需求吗？谢谢！

**Comment by lucky2077** [comment]
你可以修改 `DAEMON_URL=https://go.get... ` ，尝试一下

如果连不上RPC的话，log 里会有提示
