### ISSUE TITLE
如果我想让atomicals-js去连接本项目，ELECTRUMX_PROXY_BASE_URL该如何配置？

### ISSUE THREAD

**Issue by huangyisan** [lucky2077/atomicals-electrumx-docker#5]
我看到目前是存在两个项目，一个是当前这个项目，另外一个是[atomicals-electrumx-proxy-docker](https://github.com/Next-DAO/atomicals-electrumx-proxy-docker)项目。

我查看了当前项目的Dockerfile的编写, 里面暴露出来的50001端口为tcp，所以我是否可以认为，如果我用atomicals-js去连接本项目，那么atomicals-js里面ELECTRUMX_PROXY_BASE_URL参数，应该配置为 http://localhost:5001/proxy ?

另外我想请教下， atomicals-electrumx-proxy-docker和本项目的功能上有什么区别么？

谢谢~

**Comment by lucky2077** [comment]
proxy 项目里使用了该项目的镜像，因为官方一开始是用 websocket 接口连接的，只需要用本项目就行，当我调试好之后，发现官方又改了实现

本项目的文档仅作为参考就行，我已经在 README 做了提示，直接使用 [atomicals-electrumx-proxy-docker](https://github.com/Next-DAO/atomicals-electrumx-proxy-docker) 这个进行部署，今天也更新了一下文档

**Comment by huangyisan** [comment]
谢谢，我目前部署了官方的electrumx-proxy，已经可以正常使用。谢谢你的付出，docker非常好用！
