### ISSUE TITLE
连接的问题

### ISSUE THREAD

**Issue by weilinliao** [lucky2077/atomicals-electrumx-docker#6]
求助，连接不上，

这是bitcoin.conf
`server=1
daemon=1
txindex=1

rpcuser=atom
rpcpassword=12345678

rpcauth=electrumx:688d9662520423c3488ea92b15fc5717$d2fddc6ae335e54fa77d55c79113de6873e29b1891ba5a770c277ccb61a3db30

rpcbind=0.0.0.0
rpcbind=127.0.0.1
rpcbind=104.36.87.142
rpcallowip=127.0.0.1
rpcallowip=172.0.0.0/8
rpcallowip=104.36.87.142
`
这是 .env
`DAEMON_URL=atom:12345678@104.36.87.142:8332`

104.36.87.142 为VPS IP
![微信截图_20231115191720](https://github.com/Next-DAO/atomicals-electrumx-docker/assets/2076612/4fd4df1f-ca7c-4bf4-acda-f1846828657e)

不知道哪里出问题，谢谢

**Comment by weilinliao** [comment]
bitcoin.conf
```server=1
daemon=1
txindex=1

rpcuser=atom
rpcpassword=12345678

rpcauth=electrumx:688d9662520423c3488ea92b15fc5717$d2fddc6ae335e54fa77d55c79113de6873e29b1891ba5a770c277ccb61a3db30

rpcbind=0.0.0.0
rpcbind=127.0.0.1
rpcbind=104.36.87.142
rpcallowip=127.0.0.1
rpcallowip=172.0.0.0/8
rpcallowip=104.36.87.142
 ```
.env
`DAEMON_URL=atom:12345678@104.36.87.142:8332`

**Comment by xcpg666** [comment]
我也遇到这个问题了 请问怎么解决

**Comment by weilinliao** [comment]
> 我也遇到这个问题了请问怎么解决

看了其他大佬的教程，好像这个IP弄错了，这个IP应该填全节点所在的IP，问题是我的全节点装在本地，并没有公网IP，不知道怎么处理

**Comment by littlerookie** [comment]
> > 我也遇到这个问题了请问怎么解决
> 
> 看了其他大佬的教程，好像这个IP弄错了，这个IP应该填全节点所在的IP，问题是我的全节点装在本地，并没有公网IP，不知道怎么处理

填本地IP

**Comment by lucky2077** [comment]
104.36.87.142 确认下这台服务器的 8332 端口有没有开放

**Comment by lucky2077** [comment]
<img width="704" alt="image" src="https://github.com/Next-DAO/atomicals-electrumx-docker/assets/102849562/224b7fee-1af9-4c69-aa02-1dc96b7c6512">
