### ISSUE TITLE
ERROR:Daemon:daemon service refused: Unauthorized.  Retrying occasionally...

### ISSUE THREAD

**Issue by Ronchuan11x** [lucky2077/atomicals-electrumx-docker#7]
ERROR:Daemon:daemon service refused: Unauthorized.  Retrying occasionally...
<img width="876" alt="1700150115945" src="https://github.com/Next-DAO/atomicals-electrumx-docker/assets/116855734/1e0c96ac-9288-48f8-9823-e5acdbb4338d">

**Comment by crazythree20** [comment]
我也是这样的，监听了8000，然后我把proxy里改了，改成去访问8000，然后又报错了，显示方法无效，

**Comment by lucky2077** [comment]
bitcoin rpc 用户名 密码再检查下呢

**Comment by Ronchuan11x** [comment]
账号密码没写对，感谢

**Comment by hhfcvmars** [comment]
我这更新下，我发现我一直修改的配置的文件 /bitcoin/bitcoin.conf 一直没生效。我试了下在Bitcoin客户端打开配置文件，配置文件打开为空的配置文件，我在这空的文件输入配置就好了。

![image](https://github.com/Next-DAO/atomicals-electrumx-docker/assets/62316749/2c21a3f9-a9d9-48b6-8fa0-200f3bac48a3)

![image](https://github.com/Next-DAO/atomicals-electrumx-docker/assets/62316749/790b5bd3-9cfc-4476-834f-a231063d22e3)

**Comment by ahjohnwon** [comment]
这个错误消息 "-daemon 在这个操作系统上不受支持" 表明 -daemon 选项在你的操作系统上不受支持。-daemon 选项用于将 Bitcoin Core 作为后台进程运行，通常在类Unix系统（如Linux）上受支持。

如果你使用的是 Windows 操作系统，你不需要使用 -daemon 选项。相反，你可以将 Bitcoin Core 作为 Windows 服务运行。

以下是在 Windows 上启动 Bitcoin Core 的步骤：

以管理员身份打开命令提示符或PowerShell：
在开始菜单中右键单击命令提示符或PowerShell快捷方式，选择“以管理员身份运行”。

导航到 Bitcoin Core 安装目录：
使用 cd 命令导航到 Bitcoin Core 安装的目录。例如：

bash
Copy code
cd C:\Program Files\Bitcoin\daemon
启动 Bitcoin Core：
运行 Bitcoin Core，不使用 -daemon 选项。这将在前台启动 Bitcoin Core：

bash
Copy code
bitcoind
如果你需要指定 RPC 用户、密码和其他选项，你可以在 bitcoin.conf 配置文件中进行设置。

验证 Bitcoin Core 状态：
启动 Bitcoin Core 后，你可以通过运行以下命令来检查其状态：

bash
Copy code
bitcoin-cli getblockchaininfo
这应该显示有关区块链的信息。

确保查阅 Bitcoin Core 文档以获取与你的版本和配置相关的具体细节。如果遇到任何问题，请查看 Bitcoin Core 日志（数据目录中的 debug.log 文件），以获取有关问题的更多信息。

**Comment by ahjohnwon** [comment]
windows11直接运行 bitcoind就可以启动守护进程了  然后就解决了这个问题。上面得答案是chatgpt给出得解决方案
